# copy_text.py — every word on the page, English and Thai, written by hand.

NAV = ["what", "say", "sound", "quiz", "coconut", "y1900", "lanna", "sun", "day", "history"]

# One row per clock hour. th/ro: what people say on the hour; alt: also heard.
# mth: the stem used when minutes follow; ctx: added in brackets so 06:30 and 18:30 stay apart.
# short: the stem after "อีก … นาที" (ten to the hour). p1900: the 1900 Royal Gazette list.
# ring: strokes for the "Hear it" button — (count, instrument).
HOURS = [
    dict(h=0, th="เที่ยงคืน", ro="thiang khuen", en="noon of the night", alt="หกทุ่ม · สองยาม", alt_ro="hok thum · song yam", mth="เที่ยงคืน", mro="thiang khuen", short="เที่ยงคืน", sro="thiang khuen", p1900="สองยาม", p_ro="song yam", ring=(6, "drum"), blk="thum"),
    dict(h=1, th="ตีหนึ่ง", ro="ti nueng", en="strike 1", alt="", alt_ro="", mth="ตีหนึ่ง", mro="ti nueng", short="ตีหนึ่ง", sro="ti nueng", p1900="เจ็ดทุ่ม", p_ro="chet thum", ring=(1, "bell"), blk="ti"),
    dict(h=2, th="ตีสอง", ro="ti song", en="strike 2", alt="", alt_ro="", mth="ตีสอง", mro="ti song", short="ตีสอง", sro="ti song", p1900="แปดทุ่ม", p_ro="paet thum", ring=(2, "bell"), blk="ti"),
    dict(h=3, th="ตีสาม", ro="ti sam", en="strike 3", alt="", alt_ro="", mth="ตีสาม", mro="ti sam", short="ตีสาม", sro="ti sam", p1900="สามยาม", p_ro="sam yam", ring=(3, "bell"), blk="ti"),
    dict(h=4, th="ตีสี่", ro="ti si", en="strike 4", alt="", alt_ro="", mth="ตีสี่", mro="ti si", short="ตีสี่", sro="ti si", p1900="สิบทุ่ม", p_ro="sip thum", ring=(4, "bell"), blk="ti"),
    dict(h=5, th="ตีห้า", ro="ti ha", en="strike 5", alt="", alt_ro="", mth="ตีห้า", mro="ti ha", short="ตีห้า", sro="ti ha", p1900="สิบเอ็ดทุ่ม · ตีสิบเอ็ด", p_ro="sip-et thum · ti sip-et", ring=(5, "bell"), blk="ti"),
    dict(h=6, th="หกโมงเช้า", ro="hok mong chao", en="6 gongs, morning", alt="ย่ำรุ่ง", alt_ro="yam rung", mth="หกโมง", mro="hok mong", ctx="ตอนเช้า", cro="ton chao", short="หกโมงเช้า", sro="hok mong chao", p1900="ย่ำรุ่ง", p_ro="yam rung", ring=(0, "roll"), blk="chao"),
    dict(h=7, th="เจ็ดโมงเช้า", ro="chet mong chao", en="7 gongs, morning", alt="โมงเช้า", alt_ro="mong chao", mth="เจ็ดโมง", mro="chet mong", short="เจ็ดโมง", sro="chet mong", p1900="โมงเช้า · เช้าโมงหนึ่ง", p_ro="mong chao · chao mong nueng", ring=(1, "gong"), blk="chao"),
    dict(h=8, th="แปดโมงเช้า", ro="paet mong chao", en="8 gongs, morning", alt="สองโมงเช้า", alt_ro="song mong chao", mth="แปดโมง", mro="paet mong", short="แปดโมง", sro="paet mong", p1900="สองโมงเช้า", p_ro="song mong chao", ring=(2, "gong"), blk="chao"),
    dict(h=9, th="เก้าโมงเช้า", ro="kao mong chao", en="9 gongs, morning", alt="สามโมงเช้า", alt_ro="sam mong chao", mth="เก้าโมง", mro="kao mong", short="เก้าโมง", sro="kao mong", p1900="สามโมงเช้า", p_ro="sam mong chao", ring=(3, "gong"), blk="chao"),
    dict(h=10, th="สิบโมงเช้า", ro="sip mong chao", en="10 gongs, morning", alt="สี่โมงเช้า", alt_ro="si mong chao", mth="สิบโมง", mro="sip mong", short="สิบโมง", sro="sip mong", p1900="สี่โมงเช้า", p_ro="si mong chao", ring=(4, "gong"), blk="chao"),
    dict(h=11, th="สิบเอ็ดโมง", ro="sip-et mong", en="11 gongs", alt="ห้าโมงเช้า", alt_ro="ha mong chao", mth="สิบเอ็ดโมง", mro="sip-et mong", short="สิบเอ็ดโมง", sro="sip-et mong", p1900="ห้าโมงเช้า", p_ro="ha mong chao", ring=(5, "gong"), blk="chao"),
    dict(h=12, th="เที่ยง", ro="thiang", en="noon", alt="เที่ยงวัน", alt_ro="thiang wan", mth="เที่ยง", mro="thiang", short="เที่ยง", sro="thiang", p1900="เที่ยง · ย่ำเที่ยง", p_ro="thiang · yam thiang", ring=(0, "roll"), blk="chao"),
    dict(h=13, th="บ่ายโมง", ro="bai mong", en="afternoon, 1 gong", alt="", alt_ro="", mth="บ่ายโมง", mro="bai mong", short="บ่ายโมง", sro="bai mong", p1900="บ่ายโมง · บ่ายโมงหนึ่ง", p_ro="bai mong · bai mong nueng", ring=(1, "gong"), blk="bai"),
    dict(h=14, th="บ่ายสองโมง", ro="bai song mong", en="afternoon, 2 gongs", alt="", alt_ro="", mth="บ่ายสองโมง", mro="bai song mong", short="บ่ายสอง", sro="bai song", p1900="บ่ายสองโมง", p_ro="bai song mong", ring=(2, "gong"), blk="bai"),
    dict(h=15, th="บ่ายสามโมง", ro="bai sam mong", en="afternoon, 3 gongs", alt="", alt_ro="", mth="บ่ายสามโมง", mro="bai sam mong", short="บ่ายสาม", sro="bai sam", p1900="บ่ายสามโมง", p_ro="bai sam mong", ring=(3, "gong"), blk="bai"),
    dict(h=16, th="สี่โมงเย็น", ro="si mong yen", en="4 gongs, evening", alt="บ่ายสี่โมง", alt_ro="bai si mong", mth="บ่ายสี่โมง", mro="bai si mong", short="สี่โมงเย็น", sro="si mong yen", p1900="บ่ายสี่โมง", p_ro="bai si mong", ring=(4, "gong"), blk="bai"),
    dict(h=17, th="ห้าโมงเย็น", ro="ha mong yen", en="5 gongs, evening", alt="บ่ายห้าโมง", alt_ro="bai ha mong", mth="ห้าโมง", mro="ha mong", ctx="ตอนเย็น", cro="ton yen", short="ห้าโมงเย็น", sro="ha mong yen", p1900="บ่ายห้าโมง", p_ro="bai ha mong", ring=(5, "gong"), blk="bai"),
    dict(h=18, th="หกโมงเย็น", ro="hok mong yen", en="6 gongs, evening", alt="ย่ำค่ำ", alt_ro="yam kham", mth="หกโมง", mro="hok mong", ctx="ตอนเย็น", cro="ton yen", short="หกโมงเย็น", sro="hok mong yen", p1900="ย่ำค่ำ", p_ro="yam kham", ring=(0, "roll"), blk="bai"),
    dict(h=19, th="หนึ่งทุ่ม", ro="nueng thum", en="1 drum", alt="ทุ่มหนึ่ง", alt_ro="thum nueng", mth="หนึ่งทุ่ม", mro="nueng thum", short="หนึ่งทุ่ม", sro="nueng thum", p1900="ทุ่มหนึ่ง", p_ro="thum nueng", ring=(1, "drum"), blk="thum"),
    dict(h=20, th="สองทุ่ม", ro="song thum", en="2 drums", alt="", alt_ro="", mth="สองทุ่ม", mro="song thum", short="สองทุ่ม", sro="song thum", p1900="สองทุ่ม", p_ro="song thum", ring=(2, "drum"), blk="thum"),
    dict(h=21, th="สามทุ่ม", ro="sam thum", en="3 drums", alt="", alt_ro="", mth="สามทุ่ม", mro="sam thum", short="สามทุ่ม", sro="sam thum", p1900="ยามหนึ่ง", p_ro="yam nueng", ring=(3, "drum"), blk="thum"),
    dict(h=22, th="สี่ทุ่ม", ro="si thum", en="4 drums", alt="", alt_ro="", mth="สี่ทุ่ม", mro="si thum", short="สี่ทุ่ม", sro="si thum", p1900="สี่ทุ่ม", p_ro="si thum", ring=(4, "drum"), blk="thum"),
    dict(h=23, th="ห้าทุ่ม", ro="ha thum", en="5 drums", alt="", alt_ro="", mth="ห้าทุ่ม", mro="ha thum", short="ห้าทุ่ม", sro="ha thum", p1900="ห้าทุ่ม", p_ro="ha thum", ring=(5, "drum"), blk="thum"),
]

# Kannika Wimonkasem, Damrong Journal 1(1), 2002, p. 313: sixteen watches of 1.5 hours from 06:00.
LANNA = [
    ("ยามตูดเช้า", "yam tut chao"), ("ยามกลองงาย", "yam klong ngai"), ("ยามแตรใกล้เที่ยง", "yam trae klai thiang"), ("ยามเที่ยง", "yam thiang"),
    ("ยามตูดซ้าย", "yam tut sai"), ("ยามกลองค่ำ", "yam klong kham"), ("ยามแตรใกล้ค่ำ", "yam trae klai kham"), ("ยามค่ำ · พาดลั่น", "yam kham · phat lan"),
    ("ยามตูดดึก", "yam tut duek"), ("ยามกลองดึก", "yam klong duek"), ("ยามแตรดึก", "yam trae duek"), ("ยามดึก", "yam duek"),
    ("ยามตูดรุ่ง", "yam tut rung"), ("ยามกลองรุ่ง", "yam klong rung"), ("ยามแตรใกล้รุ่ง", "yam trae klai rung"), ("ยามรุ่ง", "yam rung"),
]

# วันไท: ten first names and twelve last names step together, one a day.
# Anchor from the 2022 Lanna calendar (Saknarin Chaongio, RMUTL): 1 Jan 2022 = กาบยี; 14, 15, 16 Apr 2022 = เมืองเร้า, เปิกเส็ด, กัดใค้.
STEMS = [("กาบ", "kap"), ("ดับ", "dap"), ("รวาย", "rwai"), ("เมือง", "mueang"), ("เปิก", "poek"), ("กัด", "kat"), ("กด", "kot"), ("ร้วง", "ruang"), ("เต่า", "tao"), ("ก่า", "ka")]
BRANCHES = [("ใจ้", "chai", "rat", "หนู"), ("เป้า", "pao", "ox", "วัว"), ("ยี", "yi", "tiger", "เสือ"), ("เหม้า", "mao", "rabbit", "กระต่าย"), ("สี", "si", "naga", "นาค"), ("ใส้", "sai", "snake", "งู"),
            ("สะง้า", "sa-nga", "horse", "ม้า"), ("เม็ด", "met", "goat", "แพะ"), ("สัน", "san", "monkey", "ลิง"), ("เร้า", "rao", "rooster", "ไก่"), ("เส็ด", "set", "dog", "หมา"), ("ใค้", "khai", "pig", "หมู")]

BANNED_1900 =["6 โมงเช้า", "6 โมงเย็น", "3 ทุ่ม", "6 ทุ่ม", "9 ทุ่ม"]

CITIES = [
    ("mhs", "Mae Hong Son", "แม่ฮ่องสอน", 19.30, 97.97),
    ("phuket", "Phuket", "ภูเก็ต", 7.88, 98.39),
    ("cm", "Chiang Mai", "เชียงใหม่", 18.79, 98.99),
    ("cr", "Chiang Rai", "เชียงราย", 19.91, 99.83),
    ("bkk", "Bangkok", "กรุงเทพฯ", 13.75, 100.50),
    ("nan", "Nan", "น่าน", 18.78, 100.78),
    ("ubon", "Ubon Ratchathani", "อุบลราชธานี", 15.24, 104.85),
]

# (headword, reading, English, Thai)
WORDS = [
    ("ตี", "ti", "To strike. The hours from 1 to 5 a.m.: ตีหนึ่ง … ตีห้า.", "การตี ใช้กับชั่วโมงตีหนึ่งถึงตีห้า"),
    ("โมง", "mong", "The boom of a gong. The daytime hours.", "เสียงฆ้อง ใช้กับชั่วโมงกลางวัน"),
    ("ทุ่ม", "thum", "The thud of a drum. The hours from 7 to 11 p.m.", "เสียงกลอง ใช้กับชั่วโมงหนึ่งทุ่มถึงห้าทุ่ม"),
    ("ย่ำ", "yam", "A long run of strokes, at 6 a.m., noon and 6 p.m. in the old names. Said with a falling tone; another word from ยาม.", "ตีรัวยาว ตอนย่ำรุ่ง ย่ำเที่ยง ย่ำค่ำ"),
    ("ยาม", "yam", "A watch: three hours of the night in central Thai, an hour and a half in Lanna.", "ช่วงเฝ้ายาม ภาคกลางยามละสามชั่วโมงตอนกลางคืน ล้านนายามละชั่วโมงครึ่ง"),
    ("เที่ยง", "thiang", "Noon. เที่ยงคืน, thiang khuen, is midnight.", "เที่ยงวัน ส่วนเที่ยงคืนคือ 24.00 น."),
    ("เช้า · บ่าย · เย็น", "chao · bai · yen", "Morning, afternoon, evening.", "ช่วงของวัน"),
    ("ค่ำ · ดึก · รุ่ง", "kham · duek · rung", "Dusk, late night, dawn.", "ช่วงของกลางคืน"),
    ("ครึ่ง", "khrueng", "Half. บ่ายสองโมงครึ่ง is 14:30.", "ครึ่งชั่วโมง"),
    ("นาฬิกา", "nalika", "A clock, and “o'clock” on the 24-hour clock. Once a coconut-shell water clock.", "เครื่องบอกเวลา และหน่วยชั่วโมงแบบ 24 ชั่วโมง เดิมคือกะลาลอย"),
    ("น.", "", "Written short for นาฬิกา: 14.30 น.", "ตัวย่อของนาฬิกา เช่น 14.30 น."),
    ("ชั่วโมง · นาที", "chuamong · nathi", "Hour (as a length of time), minute.", "หน่วยของเวลา"),
    ("บาท", "bat", "Six minutes: a tenth of an hour on the coconut clock.", "หกนาที หนึ่งในสิบของชั่วโมงบนกะลา"),
    ("คืบ", "khuep", "A hand-span, thumb to little finger.", "ระยะจากปลายนิ้วโป้งถึงปลายนิ้วก้อยเมื่อกางมือ"),
    ("เพล", "phen", "The monks' late-morning meal, eaten before noon.", "เวลาฉันอาหารของพระก่อนเที่ยง"),
]

SOURCES = [
    ("Royal Gazette vol. 17, p. 206, 29 July R.S. 119 (1900): ประกาศใช้ทุ่มโมงยาม", "https://web.archive.org/web/20120609235147/http://www.ratchakitcha.soc.go.th/DATA/PDF/2443/018/206.PDF"),
    ("Kannika Wimonkasem, ศักราช ศก ปี วัน เดือน ฤกษ์ และยามในจารึกล้านนา, Damrong Journal 1(1), 2002", "https://so01.tci-thaijo.org/index.php/damrong/article/view/21390"),
    ("Phisansri Kratai-thong, หอสูงกับการบอกเวลา, Silpa Wattanatham, October 2015 (online excerpt)", "https://www.silpa-mag.com/history/article_7703"),
    ("Silpa Wattanatham, คำเรียกเวลา โมง-ทุ่ม มาจากไหน ใครกำหนด?", "https://www.silpa-mag.com/culture/article_122812"),
    ("Saknarin Chaongio, ปฏิทินล้านนา 2565 (Lanna calendar 2022), Rajamangala University of Technology Lanna", "https://sdgs.rmutl.ac.th/wp-content/uploads/2023/10/ปฏิทินล้านนา-2565.pdf"),
    ("Wikipedia: Thai six-hour clock", "https://en.wikipedia.org/wiki/Thai_six-hour_clock"),
    ("วิกิพีเดีย: นาฬิกาหกชั่วโมง", "https://th.wikipedia.org/wiki/นาฬิกาหกชั่วโมง"),
    ("Wikipedia: Time in Thailand", "https://en.wikipedia.org/wiki/Time_in_Thailand"),
    ("Hydrographic Department, Royal Thai Navy (standard time)", "https://www.hydro.navy.mi.th/"),
    ("NOAA solar calculation details", "https://gml.noaa.gov/grad/solcalc/calcdetails.html"),
]

PHOTO_TEXT = {
    "drum-tower": ("Bangkok's drum tower, four storeys of brick, beside Charoen Krung Road, photographed from the palace clock tower, 1922.", "หอกลองของกรุงเทพฯ หอก่ออิฐสี่ชั้นริมถนนเจริญกรุง ถ่ายจากพระที่นั่งภูวดลทัศไนย พ.ศ. 2465"),
    "clock-tower": ("Phuwadon Thatsanai, the clock tower in the Grand Palace, 1922.", "พระที่นั่งภูวดลทัศไนย หอนาฬิกาในพระบรมมหาราชวัง พ.ศ. 2465"),
    "khong-mong": ("A ฆ้องโมง khong mong hangs from its tripod at left, 1931, with gongs built from it.", "ฆ้องโมงแขวนบนขาตั้งสามขาทางซ้าย พ.ศ. 2474 กับฆ้องชนิดอื่นที่ดัดแปลงมาจากฆ้องโมง"),
}

UI = {
    "en": {
        "title": "Telling Time in Thai",
        "other_title": "บอกเวลาแบบไทย",
        "desc": "How Thai people tell time: the six-hour spoken clock named for a gong by day and a drum by night, the 24-hour clock on paper, the king's list of 1900, the coconut water clock, Lanna's sixteen watches and noon by the sun. A live dial, sounds and a quiz, in English and Thai.",
        "card_alt": "A 24-hour dial in gold, coral and violet, with the title Telling Time in Thai",
        "hero_alt": "A 24-hour dial split into four six-hour blocks, with the hand on the time now in Thailand",
        "kicker": "ตี · โมง · ทุ่ม — strike, gong, drum",
        "lede": "Thailand runs two clocks at once: the 24-hour clock on paper, and in speech an older count of six-hour blocks, named for a gong by day and a drum by night.",
        "now_lab": "Now in Thailand",
        "hero_go": "Turn the dial",
        "cardline": "Gong by day, drum by night",
        "nav_label": "Sections",
        "nav": ["Two clocks", "Say it", "Gong & drum", "Quiz", "Coconut", "1900", "Lanna", "Sun", "A day", "History"],
        "lang_this": "EN",
        "lang_other": ("th/", "ไทย", "th"),

        "what_kick": "Six-hour clock",
        "what_h": "Two clocks at once",
        "what_p": [
            "Written down, Thai time runs on the 24-hour clock: 14.30 น., read <i>sip-si nalika sam-sip nathi</i>. Said out loud it mostly runs on an older count: <b lang=th>บ่ายสองโมงครึ่ง</b>, <i>bai song mong khrueng</i>, “afternoon, two gongs, half”.",
            "The spoken count cuts the day into four blocks of six hours and starts again at one in each block. Each block has its own word, and the words are sounds. <b lang=th>โมง</b> <i>mong</i> is the boom of a gong, struck through the day. <b lang=th>ทุ่ม</b> <i>thum</i> is the thud of a drum, struck through the evening. <b lang=th>ตี</b> <i>ti</i>, “strike”, takes the small hours.",
            "So 2 a.m. is <b lang=th>ตีสอง</b>, 8 a.m. is <b lang=th>แปดโมง</b>, 2 p.m. is <b lang=th>บ่ายสองโมง</b> and 8 p.m. is <b lang=th>สองทุ่ม</b>. Pick the wrong block and you turn up six hours early, or twelve hours late.",
        ],
        "blocks": [
            ("ti", "ตี", "ti", "01–05", "strike · after midnight", "ตีหนึ่ง … ตีห้า"),
            ("chao", "โมงเช้า", "mong chao", "06–11", "gong · morning", "หกโมงเช้า, เจ็ดโมง … สิบเอ็ดโมง"),
            ("bai", "บ่าย · เย็น", "bai · yen", "13–18", "afternoon · evening", "บ่ายโมง … หกโมงเย็น"),
            ("thum", "ทุ่ม", "thum", "19–23", "drum · night", "หนึ่งทุ่ม … ห้าทุ่ม"),
        ],
        "blocks_note": "Noon is <b lang=th>เที่ยง</b> <i>thiang</i>; midnight is <b lang=th>เที่ยงคืน</b> <i>thiang khuen</i>, the noon of the night.",
        "hours_h": "Every hour",
        "hours_cols": ["Clock", "Said", "Reading", "Word by word", "Also heard"],

        "say_kick": "Turn the dial",
        "say_h": "Say any time",
        "say_p": ["Drag the hand or slide the bar. The page writes that time the way people say it, the way the palace listed it in 1900, the way the radio reads it, and the Lanna watch it falls in."],
        "r_spoken": "Spoken",
        "r_also": "Also heard",
        "r_1900": "Palace list, 1900",
        "r_radio": "Radio and paper",
        "r_written": "Written",
        "r_lanna": "Lanna watch",
        "b_now": "Now",
        "b_hear": "Hear it",
        "say_note": "Half past is <b lang=th>ครึ่ง</b> <i>khrueng</i>. Other minutes take the number and <b lang=th>นาที</b> <i>nathi</i>. Near the hour people count down: <b lang=th>อีกสิบนาทีสามทุ่ม</b>, “ten more minutes to three drums”. The 1900 column counts minutes in บาท of six minutes, the old water-clock unit. Hear it plays a gong for โมง, a drum for ทุ่ม, a small bell for ตี and a fast roll for the six o'clocks and noon.",

        "sound_kick": "Where the words come from",
        "sound_h": "Gong by day, drum by night",
        "sound_p": [
            "Before clocks, the hours came from a tower. Keepers struck a gong (<b lang=th>ฆ้อง</b> <i>khong</i>) through the day and beat a drum (<b lang=th>กลอง</b> <i>klong</i>) through the night, once for each hour into the block. People named the hour by what they heard: โมง for the gong, ทุ่ม for the drum.",
            "At 6 a.m., noon and 6 p.m. the keepers beat a long run of strokes, <b lang=th>ย่ำ</b> <i>yam</i>: dawn was <b lang=th>ย่ำรุ่ง</b>, noon <b lang=th>ย่ำเที่ยง</b>, dusk <b lang=th>ย่ำค่ำ</b>. In Ayutthaya the big drum at the foot of the drum tower was beaten at sunset to close the city gates.",
        ],
        "s_gong": "Gong",
        "s_drum": "Drum",
        "s_roll": "ย่ำ roll",
        "s_horn": "Lanna horn",
        "sound_note": "Your browser makes these sounds from a few sine waves and a burst of noise. They are drawn sounds, not recordings.",

        "quiz_kick": "Quiz",
        "quiz_h": "Try it",
        "quiz_p": ["Eight questions. The wrong answers are the usual mix-ups: the same number in another block."],
        "q_which_time": "What time is",
        "q_which_say": "How do you say",
        "q_next": "Next",
        "q_again": "Again",
        "q_right": "Right.",
        "q_wrong": "Not quite. It is",
        "q_score": "Score",
        "q_done": "Done",

        "coconut_kick": "Water clock",
        "coconut_h": "The coconut that sinks",
        "coconut_p": [
            "<b lang=th>นาฬิกา</b> <i>nalika</i>, now the word for a clock, first meant a coconut. Siam kept time with a <b lang=th>กะลาลอย</b> <i>kala loi</i>: half a coconut shell with a small hole in the bottom, floated in a basin. Water seeps in, the shell rides lower, and when it is full it sinks. One sinking, one hour.",
            "Keepers scored the shell with nine lines into ten parts, each a <b lang=th>บาท</b> <i>bat</i> of six minutes. In the palace clock house, each time the shell sank a keeper struck the gong once and pushed a tally stick onto a rail. Twelve sticks made a day or a night; the rail was cleared at dawn and at dusk.",
            "This shell is a half sphere, and it floats, so it rides lower as it fills. Water pushes in through the hole faster the higher the level outside stands above the level inside (Torricelli's law: the speed grows with the square root of that drop). The gap narrows as the bowl widens, so the shell fills more slowly toward the end; the nine lines here sit at equal times under that rule. The shell sinks when its rim reaches the water, before it is full.",
        ],
        "coconut_quote": "King Mongkut (Rama IV) grumbled that the keepers guessed, calling ten บาท to the hour whatever the season, “…คงให้ได้ว่าความแต่ว่าโมงละ ๑๐ บาทอยู่นั้นเอง…”, and that visitors carrying pocket watches would laugh at hours struck short and long.",
        "c_speed": ["Real time", "1 hour a minute", "1 hour in 6 s"],
        "c_bat": "บาท",
        "c_min": "Minutes",
        "c_sticks": "Sticks on the rail",

        "y1900_kick": "Royal Gazette",
        "y1900_h": "The king's list, 1900",
        "y1900_p": [
            "On 23 July 1900 King Chulalongkorn (Rama V) had the hour names printed in the Royal Gazette. People had drifted, it said, and were saying 6 โมงเช้า, 6 โมงเย็น, 3 ทุ่ม, 6 ทุ่ม and 9 ทุ่ม. The list set them right.",
            "In the king's list the drum count runs all night, up to eleven: 1 a.m. is <b lang=th>เจ็ดทุ่ม</b>, seven drums. Three points of the night get their own names: <b lang=th>ยามหนึ่ง</b> at 9 p.m., <b lang=th>สองยาม</b> at midnight, <b lang=th>สามยาม</b> at 3 a.m. A <b lang=th>ยาม</b> <i>yam</i> is a watch of three hours.",
            "Today people say all five of the forms the list struck out, and ตี has taken the small hours from the drum.",
        ],
        "y_cols": ["Clock", "Said today", "King's list, 1900"],
        "y_banned": "Struck out in 1900",
        "y1900_note": "Royal Gazette volume 17, page 206, dated 29 July, Rattanakosin year 119: 1900. English Wikipedia gives 1901.",

        "lanna_kick": "The north",
        "lanna_h": "Lanna time: watches, not hours",
        "lanna_p": [
            "The old Lanna count has no 60-minute hour. Inscriptions cut the day into sixteen watches, <b lang=th>ยาม</b> <i>yam</i>, of an hour and a half: eight by day and eight by night, from 6 a.m. A watch takes its name from the instrument that signalled it, then the part of the day. <b lang=th>ตูด</b> <i>tut</i> is a buffalo horn blown; <b lang=th>กลอง</b> <i>klong</i> the drum; <b lang=th>แตร</b> <i>trae</i> a horn or trumpet.",
            "<b lang=th>ยามกลองงาย</b>, the morning-meal drum, runs from 7.30 to 9 a.m. The four watches found most in Lanna inscriptions all fall between dawn and early afternoon: ยามตูดเช้า, ยามกลองงาย, ยามแตรใกล้เที่ยง and ยามตูดซ้าย. Kannika Wimonkasem, who listed them, reads that as the hours chosen for ceremonies.",
        ],
        "l_day": "Day",
        "l_night": "Night",
        "l_now": "Now",
        "lanna_note": "Names and hours from Kannika Wimonkasem, Damrong Journal, 2002. Inscriptions from Isan and Laos use some other names.",
        "lcal_h": "Still in the calendar",
        "lcal_p": [
            "Lanna calendars still time the big moments by watch. The 2022 Lanna calendar compiled by Saknarin Chaongio at Rajamangala University of Technology Lanna puts Songkran in <b lang=th>ยามแตรสู่เที่ยง</b>, the horn watch toward noon, at 9.52.12 a.m. on 14 April, and the turn of the era year in <b lang=th>ยามกลองแลง</b>, the late-day drum, at 1.49.48 p.m. on 16 April. Both clock times fall inside the watches in the table above. <b lang=th>แลง</b> <i>laeng</i> is the northern word for late afternoon.",
            "Five hundred years earlier, in 1502, an inscription at Wat Doi Kham in Lamphun dates its horoscope <b lang=th>ยามแตรจักใกล้เที่ยง</b>, “the horn watch, near noon”.",
        ],
        "days_h": "Sixty named days",
        "days_p": [
            "Lanna also names each day from a cycle of sixty, the <b lang=th>วันไท</b> <i>wan thai</i>, “Tai day”. Ten first names and twelve last names turn together, one step a day, like two gears: กาบยี, ดับเหม้า, รวายสี, เมืองใส้ … The gears line up again after 60 days.",
            "Both gears step at once, and 10 and 12 are both even, so a first name only ever meets every other last name: 60 of the 120 possible pairs occur. The years turn on the same two gears; the era year 1388, which began in April 2026, is <b lang=th>ปีรวายสะง้า</b>, a horse year.",
        ],
        "d_today": "Today",
        "d_prev": "Day before",
        "d_next": "Day after",
        "d_year": "Era year",
        "days_note": "Counted from the 2022 Lanna calendar, where 1 January 2022 is กาบยี and 14, 15 and 16 April are เมืองเร้า, เปิกเส็ด and กัดใค้. The page counts by the civil date; the era year turns in mid-April.",
        "months_h": "Months two ahead",
        "months_p": [
            "Lanna numbers its lunar months two ahead of central Thailand. Yi Peng, <b lang=th>ยี่เป็ง</b>, is the full moon of the second month in the north and of the twelfth in Bangkok. Tai Lue and Tai Khuen towns, Mae Sai, Chiang Khong, Chiang Kham and northern Nan among them, count <b lang=th>เดือนโหรา</b> <i>duean hora</i>, one month ahead of Bangkok and one behind the rest of Lanna.",
        ],

        "sun_kick": "Sun time",
        "sun_h": "Noon by the sun",
        "sun_p": [
            "Thai clocks run on the 105th meridian east, the line through Ubon Ratchathani. Until 1 April 1920 Siam kept Bangkok's own sun time, 6 hours 42 minutes 4 seconds ahead of Greenwich; that night the clocks jumped 17 minutes 56 seconds.",
            "Chiang Mai sits six degrees west of the line, so its sun peaks about 24 minutes after clock noon, more or less with the season. Pick a town.",
            "In the northern forests people read the hour off the sun by hand: arm out, fingers spread, count hand-spans (<b lang=th>คืบ</b> <i>khuep</i>) up from the horizon. One span, one โมง; six spans, noon.",
        ],
        "u_rise": "Sunrise",
        "u_noon": "Sun's noon",
        "u_set": "Sunset",
        "u_spans": "Hand-spans now",
        "u_line": "105°E · clock time",
        "u_bmt": "Bangkok sun time until 1920",
        "u_down": "below the horizon",
        "sun_note": "Sun from the NOAA solar equations; sunrise and sunset for the sun's top edge, allowing for air bending the light.",

        "day_kick": "Daily round",
        "day_h": "A day by the clock",
        "day": [
            ("04:00", "ตีสี่", "Many temples wake; monks chant the morning service."),
            ("06:00", "หกโมงเช้า", "Monks walk the alms round, <b lang=th>บิณฑบาต</b> <i>binthabat</i>, in the first light."),
            ("08:00", "แปดโมงเช้า", "The national anthem plays on radio, TV and loudspeakers; the flag goes up and people stand still where they are."),
            ("11:00", "สิบเอ็ดโมง", "<b lang=th>เพล</b> <i>phen</i>: the monks' last meal of the day, finished before noon."),
            ("12:00", "เที่ยง", "Lunch for everyone else: <b lang=th>ข้าวเที่ยง</b> <i>khao thiang</i>."),
            ("—", "บ่ายควาย", "Old sun-time phrases: <b lang=th>บ่ายควาย</b>, “buffalo afternoon”, and <b lang=th>ควายเข้าคอก</b>, “buffalo into the pen”, for late in the day."),
            ("18:00", "หกโมงเย็น", "The anthem again; the flag comes down."),
            ("00:00", "เที่ยงคืน", "The noon of the night. In the 1900 list, สองยาม, the end of the second watch."),
        ],

        "pic_h": "Pictures",
        "hist_kick": "History",
        "hist_h": "From drum tower to radio",
        "hist": [
            ("Ayutthaya", "A drum tower ten wa high, four storeys, held three drums: ย่ำพระสุรศรี at the foot, beaten at sunset to close the gates; อัคคีพินาศ in the middle for fire; พิฆาตไพรินทร์ at the top for an enemy at the walls."),
            ("Rama I", "Trials by diving were timed with a sinking coconut. The king worried over a shell that sank before either diver came up, and had a gong signal used instead."),
            ("Rama II", "Small watches arrived as Portuguese gifts. With no shirt pockets, people tucked them into the fold of the waist-cloth, the <b lang=th>พก</b> <i>phok</i>: so a pocket watch is <b lang=th>นาฬิกาพก</b>."),
            ("Rama IV", "King Mongkut set up a clock office in the palace, compared its pendulum clocks against the sundial at noon, and had the hour names announced in the Royal Gazette."),
            ("1889", "The solar calendar becomes the government calendar, the year starting on 1 April."),
            ("1900", "Rama V's announcement ประกาศใช้ทุ่มโมงยาม lists the hour names and strikes out five common mistakes."),
            ("Noon gun", "The navy fired a gun at noon so the city could set its clocks; later the power station blinked the lights at สองทุ่ม instead."),
            ("1920", "On 1 April Siam moves from Bangkok's sun time to the 105th meridian, UTC+7."),
            ("Today", "The Royal Thai Navy's Hydrographic Department keeps Thailand's standard time; radio and TV read it at 08:00 and 18:00 with the anthem."),
        ],
        "words_h": "Words",
        "src_h": "Sources",
        "src_p": "Hour names from the Royal Gazette of 1900 and the Thai and English Wikipedia articles; Lanna watches from Kannika Wimonkasem; coconut clock, drum tower and noon gun from Phisansri Kratai-thong in Silpa Wattanatham.",
        "foot": "Text CC BY 4.0, NaNoBotCo. Code MIT. Pictures public domain, from Wikimedia Commons.",
        "js": {
            "on": "on", "gong": "gong", "drum": "drum", "bell": "bell", "roll": "roll",
            "bat": "บาท", "min": "min", "to": "to", "spans": "spans", "noon": "noon",
            "blk": {"ti": "ตี", "chao": "โมงเช้า", "bai": "บ่าย · เย็น", "thum": "ทุ่ม"},
            "midnight": "midnight", "noon_w": "noon", "cs": "CS",
            "gloss": {"half": "half", "min": "minutes", "more": "more", "to": "to"},
        },
    },
    "th": {
        "title": "บอกเวลาแบบไทย",
        "other_title": "Telling Time in Thai",
        "desc": "คนไทยบอกเวลาอย่างไร นาฬิกาหกชั่วโมงที่พูดกัน ตั้งชื่อตามเสียงฆ้องตอนกลางวันและเสียงกลองตอนกลางคืน นาฬิกา 24 ชั่วโมงบนกระดาษ ประกาศ ร.ศ. 119 กะลาลอย สิบหกยามของล้านนา และเที่ยงตามแดด มีหน้าปัดสด เสียง และเกมทายเวลา ภาษาไทยและอังกฤษ",
        "card_alt": "หน้าปัด 24 ชั่วโมงสีทอง ชมพู และม่วง กับชื่อ บอกเวลาแบบไทย",
        "hero_alt": "หน้าปัด 24 ชั่วโมงแบ่งเป็นสี่ช่วง ช่วงละหกชั่วโมง เข็มชี้เวลาตอนนี้ที่เมืองไทย",
        "kicker": "ตี · โมง · ทุ่ม",
        "lede": "เมืองไทยใช้นาฬิกาสองแบบพร้อมกัน แบบ 24 ชั่วโมงบนกระดาษ กับแบบหกชั่วโมงที่พูดกัน ตั้งชื่อตามเสียงฆ้องตอนกลางวันและเสียงกลองตอนกลางคืน",
        "now_lab": "ตอนนี้ที่เมืองไทย",
        "hero_go": "หมุนหน้าปัด",
        "cardline": "กลางวันฆ้อง กลางคืนกลอง",
        "nav_label": "หัวข้อ",
        "nav": ["สองนาฬิกา", "พูดเวลา", "ฆ้องกับกลอง", "ทายเวลา", "กะลาลอย", "ร.ศ. 119", "ล้านนา", "แดด", "หนึ่งวัน", "ประวัติ"],
        "lang_this": "ไทย",
        "lang_other": ("../", "EN", "en"),

        "what_kick": "นาฬิกาหกชั่วโมง",
        "what_h": "นาฬิกาสองแบบ",
        "what_p": [
            "เวลาที่เขียน ใช้แบบ 24 ชั่วโมง เช่น 14.30 น. อ่านว่า สิบสี่นาฬิกาสามสิบนาที แต่เวลาที่พูด คนส่วนใหญ่ใช้แบบเก่า คือ <b>บ่ายสองโมงครึ่ง</b>",
            "แบบที่พูดแบ่งวันเป็นสี่ช่วง ช่วงละหกชั่วโมง แต่ละช่วงเริ่มนับหนึ่งใหม่ และมีคำของตัวเอง คำเหล่านี้มาจากเสียง <b>โมง</b> คือเสียงฆ้องที่ตีตอนกลางวัน <b>ทุ่ม</b> คือเสียงกลองที่ตีตอนค่ำ <b>ตี</b> ใช้กับช่วงหลังเที่ยงคืน",
            "ตีสองคือ 02:00 แปดโมงคือ 08:00 บ่ายสองโมงคือ 14:00 สองทุ่มคือ 20:00 ถ้าจำช่วงผิด อาจไปถึงก่อนเวลาหกชั่วโมง หรือช้าไปสิบสองชั่วโมง",
        ],
        "blocks": [
            ("ti", "ตี", "ti", "01–05", "หลังเที่ยงคืน", "ตีหนึ่ง … ตีห้า"),
            ("chao", "โมงเช้า", "mong chao", "06–11", "ตอนเช้า", "หกโมงเช้า, เจ็ดโมง … สิบเอ็ดโมง"),
            ("bai", "บ่าย · เย็น", "bai · yen", "13–18", "ตอนบ่ายถึงเย็น", "บ่ายโมง … หกโมงเย็น"),
            ("thum", "ทุ่ม", "thum", "19–23", "ตอนค่ำ", "หนึ่งทุ่ม … ห้าทุ่ม"),
        ],
        "blocks_note": "12.00 น. คือ <b>เที่ยง</b> และ 24.00 น. คือ <b>เที่ยงคืน</b>",
        "hours_h": "ทุกชั่วโมง",
        "hours_cols": ["เวลา", "พูดว่า", "อ่านแบบอักษรโรมัน", "แปลทีละคำ", "พูดอีกแบบ"],

        "say_kick": "หมุนหน้าปัด",
        "say_h": "พูดเวลาไหนก็ได้",
        "say_p": ["ลากเข็มหรือเลื่อนแถบ หน้านี้จะเขียนเวลานั้นแบบที่คนพูด แบบที่ในวังกำหนดไว้เมื่อ พ.ศ. 2443 แบบที่วิทยุอ่าน และบอกว่าตรงกับยามไหนของล้านนา"],
        "r_spoken": "พูดกันทั่วไป",
        "r_also": "พูดอีกแบบ",
        "r_1900": "ประกาศ ร.ศ. 119",
        "r_radio": "วิทยุและหนังสือราชการ",
        "r_written": "เขียน",
        "r_lanna": "ยามล้านนา",
        "b_now": "ตอนนี้",
        "b_hear": "ฟังเสียง",
        "say_note": "ครึ่งชั่วโมงพูดว่า <b>ครึ่ง</b> นาทีอื่นพูดตัวเลขตามด้วย <b>นาที</b> ใกล้ครบชั่วโมงมักนับถอยหลัง เช่น <b>อีกสิบนาทีสามทุ่ม</b> ช่องประกาศ ร.ศ. 119 นับนาทีเป็นบาท บาทละหกนาที ตามหน่วยของกะลาลอย ปุ่มฟังเสียงตีฆ้องสำหรับโมง ตีกลองสำหรับทุ่ม เคาะกระดิ่งเล็กสำหรับตี และตีรัวสำหรับหกโมงเช้า เที่ยง และหกโมงเย็น",

        "sound_kick": "คำมาจากไหน",
        "sound_h": "กลางวันฆ้อง กลางคืนกลอง",
        "sound_p": [
            "ก่อนจะมีนาฬิกา เวลามาจากหอ คนเฝ้าตี<b>ฆ้อง</b>ตอนกลางวัน และตี<b>กลอง</b>ตอนกลางคืน ตีเท่าจำนวนชั่วโมงที่ผ่านไปในช่วงนั้น คนจึงเรียกชั่วโมงตามเสียงที่ได้ยิน โมงจากฆ้อง ทุ่มจากกลอง",
            "ตอนหกโมงเช้า เที่ยง และหกโมงเย็น คนเฝ้าตีรัวยาว เรียกว่า <b>ย่ำ</b> จึงมีคำว่า ย่ำรุ่ง ย่ำเที่ยง ย่ำค่ำ ที่กรุงศรีอยุธยา กลองใบใหญ่ชั้นล่างของหอกลองตีตอนพระอาทิตย์ตก เป็นสัญญาณปิดประตูเมือง",
        ],
        "s_gong": "ฆ้อง",
        "s_drum": "กลอง",
        "s_roll": "ย่ำ",
        "s_horn": "ตูด (เขาควาย)",
        "sound_note": "เสียงเหล่านี้เบราว์เซอร์สร้างขึ้นจากคลื่นไม่กี่เส้นกับเสียงซ่า เป็นเสียงวาด ไม่ใช่เสียงอัด",

        "quiz_kick": "ลองตอบ",
        "quiz_h": "ทายเวลา",
        "quiz_p": ["แปดข้อ คำตอบผิดคือคำที่คนสับสนกันบ่อย ตัวเลขเดียวกันแต่อยู่คนละช่วง"],
        "q_which_time": "เวลาไหนคือ",
        "q_which_say": "พูดอย่างไร",
        "q_next": "ข้อต่อไป",
        "q_again": "เล่นใหม่",
        "q_right": "ถูก",
        "q_wrong": "ยังไม่ใช่ คำตอบคือ",
        "q_score": "คะแนน",
        "q_done": "จบแล้ว",

        "coconut_kick": "นาฬิกาน้ำ",
        "coconut_h": "กะลาที่จมทุกชั่วโมง",
        "coconut_p": [
            "คำว่า <b>นาฬิกา</b> เดิมแปลว่ามะพร้าว สยามจับเวลาด้วย <b>กะลาลอย</b> คือกะลาครึ่งซีกเจาะรูเล็ก ๆ ที่ก้น ลอยไว้ในอ่างน้ำ น้ำซึมเข้า กะลาจมลงทีละนิด พอเต็มก็จม จมหนึ่งครั้งเท่ากับหนึ่งชั่วโมง",
            "คนทำบากเส้นในกะลาเก้าเส้น แบ่งเป็นสิบส่วน ส่วนละหนึ่ง <b>บาท</b> เท่ากับหกนาที ที่โรงนาฬิกาในวัง ทุกครั้งที่กะลาจม คนเฝ้าตีฆ้องหนึ่งที และปักไม้คะแนนบนราวหนึ่งอัน ครบสิบสองอันคือหนึ่งกลางวันหรือหนึ่งกลางคืน ถอนออกตอนย่ำรุ่งและย่ำค่ำ",
            "กะลาในภาพนี้เป็นครึ่งทรงกลมที่ลอยอยู่ ยิ่งน้ำเข้าก็ยิ่งจมลึก น้ำไหลเข้ารูเร็วเมื่อระดับน้ำข้างนอกสูงกว่าข้างในมาก (กฎของตอร์ริเชลลี ความเร็วโตตามรากที่สองของระยะนั้น) ระยะนี้แคบลงเมื่อกะลากว้างขึ้น กะลาจึงเต็มช้าลงตอนท้าย เส้นบากเก้าเส้นในภาพวางตามเวลาที่เท่ากันตามกฎนี้ กะลาจมเมื่อขอบลงถึงระดับน้ำ ก่อนน้ำจะเต็ม",
        ],
        "coconut_quote": "รัชกาลที่ 4 ทรงบ่นว่าพนักงานกะบาทเอาเอง ไม่ว่าฤดูไหน “…คงให้ได้ว่าความแต่ว่าโมงละ ๑๐ บาทอยู่นั้นเอง…” และทรงเกรงว่าแขกเมืองที่พกนาฬิกาจะหัวเราะเยาะทุ่มโมงที่ตีสั้นบ้างยาวบ้าง",
        "c_speed": ["เวลาจริง", "ชั่วโมงละ 1 นาที", "ชั่วโมงละ 6 วินาที"],
        "c_bat": "บาท",
        "c_min": "นาที",
        "c_sticks": "ไม้คะแนนบนราว",

        "y1900_kick": "ราชกิจจานุเบกษา",
        "y1900_h": "ประกาศใช้ทุ่มโมงยาม ร.ศ. 119",
        "y1900_p": [
            "วันที่ 23 กรกฎาคม ร.ศ. 119 (พ.ศ. 2443) รัชกาลที่ 5 โปรดให้ลงประกาศในราชกิจจานุเบกษา ว่าคนเรียกทุ่มโมงยามผิดเพี้ยนไป พูดว่า 6 โมงเช้า 6 โมงเย็น 3 ทุ่ม 6 ทุ่ม 9 ทุ่ม จึงให้เรียกให้ถูกตามรายการ",
            "ในรายการนี้ กลองนับไปทั้งคืนจนถึงสิบเอ็ด ตีหนึ่งคือ <b>เจ็ดทุ่ม</b> และกลางคืนมีชื่อเฉพาะสามจุด <b>ยามหนึ่ง</b> คือ 21.00 น. <b>สองยาม</b> คือเที่ยงคืน <b>สามยาม</b> คือ 03.00 น. <b>ยาม</b> คือช่วงเฝ้ายาม ยามละสามชั่วโมง",
            "ทุกวันนี้คนพูดทั้งห้าคำที่ประกาศว่าผิด และ ตี เข้ามาแทนกลองในช่วงหลังเที่ยงคืน",
        ],
        "y_cols": ["เวลา", "พูดวันนี้", "ประกาศ ร.ศ. 119"],
        "y_banned": "คำที่ประกาศว่าผิด",
        "y1900_note": "ราชกิจจานุเบกษา เล่ม 17 หน้า 206 วันที่ 29 กรกฎาคม ร.ศ. 119 ตรงกับ ค.ศ. 1900 วิกิพีเดียภาษาอังกฤษเขียนว่า 1901",

        "lanna_kick": "ล้านนา",
        "lanna_h": "เวลาล้านนา นับเป็นยาม ไม่ใช่ชั่วโมง",
        "lanna_p": [
            "การนับแบบล้านนาเดิมไม่มีชั่วโมงละ 60 นาที จารึกล้านนาแบ่งวันเป็นสิบหก<b>ยาม</b> ยามละชั่วโมงครึ่ง กลางวันแปด กลางคืนแปด เริ่มที่หกโมงเช้า ชื่อยามมาจากเครื่องที่ใช้ให้สัญญาณ ตามด้วยช่วงของวัน <b>ตูด</b> คือเป่าเขาควาย <b>กลอง</b> คือตีกลอง <b>แตร</b> คือเป่าแตร",
            "<b>ยามกลองงาย</b> คือตีกลองบอกเวลาข้าวเช้า 07.30–09.00 น. ยามที่พบในจารึกล้านนามากที่สุดสี่ยาม อยู่ระหว่างรุ่งเช้าถึงบ่ายต้น ๆ ทั้งหมด คือ ยามตูดเช้า ยามกลองงาย ยามแตรใกล้เที่ยง และยามตูดซ้าย อาจารย์กรรณิการ์ วิมลเกษม ผู้รวบรวม เห็นว่าเป็นเพราะเป็นยามที่เหมาะกับพิธีมงคล",
        ],
        "l_day": "กลางวัน",
        "l_night": "กลางคืน",
        "l_now": "ตอนนี้",
        "lanna_note": "ชื่อและเวลาจาก กรรณิการ์ วิมลเกษม วารสารดำรงวิชาการ พ.ศ. 2545 จารึกอีสานและลาวใช้ชื่อต่างไปบางชื่อ",
        "lcal_h": "ยังอยู่ในปฏิทิน",
        "lcal_p": [
            "ปฏิทินล้านนายังบอกเวลาสำคัญเป็นยาม ปฏิทินล้านนา 2565 ที่ ศักดิ์นรินทร์ ชาวงิ้ว จัดทำ เผยแพร่โดยมหาวิทยาลัยเทคโนโลยีราชมงคลล้านนา บอกว่าสังขานต์ล่องตกใน<b>ยามแตรสู่เที่ยง</b> เวลา 9 นาฬิกา 52 นาที 12 วินาที วันที่ 14 เมษายน และศักราชขึ้นใน<b>ยามกลองแลง</b> เวลา 13 นาฬิกา 49 นาที 48 วินาที วันที่ 16 เมษายน เวลาทั้งสองอยู่ในช่วงยามตามตารางข้างบน <b>แลง</b> คือคำเมืองของช่วงบ่ายแก่ถึงเย็น",
            "ห้าร้อยปีก่อนหน้านั้น จารึกวัดดอยคำ ลำพูน พ.ศ. 2045 บอกเวลาของดวงชาตาว่า <b>ยามแตรจักใกล้เที่ยง</b>",
        ],
        "days_h": "หกสิบชื่อวัน",
        "days_p": [
            "ล้านนายังตั้งชื่อวันจากรอบหกสิบ เรียกว่า <b>วันไท</b> ชื่อหน้าสิบชื่อกับชื่อหลังสิบสองชื่อหมุนไปพร้อมกันวันละหนึ่งก้าว เหมือนเฟืองสองตัว กาบยี ดับเหม้า รวายสี เมืองใส้ … ครบหกสิบวันเฟืองจึงกลับมาตรงกัน",
            "เฟืองทั้งสองหมุนพร้อมกัน และ 10 กับ 12 เป็นเลขคู่ทั้งคู่ ชื่อหน้าแต่ละชื่อจึงพบชื่อหลังได้แค่ครึ่งเดียว จาก 120 คู่ที่เป็นไปได้ เกิดจริง 60 คู่ ปีก็หมุนด้วยเฟืองคู่เดียวกัน จุลศักราช 1388 ที่ขึ้นเมื่อเมษายน 2569 คือ <b>ปีรวายสะง้า</b> ปีม้า",
        ],
        "d_today": "วันนี้",
        "d_prev": "วันก่อน",
        "d_next": "วันถัดไป",
        "d_year": "ปี จ.ศ.",
        "days_note": "นับจากปฏิทินล้านนา 2565 ซึ่ง 1 มกราคม 2565 คือวันกาบยี และ 14, 15, 16 เมษายน คือ เมืองเร้า เปิกเส็ด กัดใค้ หน้านี้นับตามวันที่ตามปฏิทินสากล จุลศักราชขึ้นปีใหม่กลางเดือนเมษายน",
        "months_h": "เดือนเร็วกว่าสองเดือน",
        "months_p": [
            "ล้านนานับเดือนทางจันทรคติเร็วกว่าภาคกลางสองเดือน <b>ยี่เป็ง</b> คือเพ็ญเดือนยี่ของทางเหนือ ตรงกับเพ็ญเดือนสิบสองของภาคกลาง ส่วนเมืองไทลื้อและไทขืน เช่น แม่สาย เชียงของ เชียงคำ และน่านตอนบน นับ<b>เดือนโหรา</b> เร็วกว่าภาคกลางหนึ่งเดือน และช้ากว่าเดือนปากเล้มของล้านนาหนึ่งเดือน",
        ],

        "sun_kick": "เวลาตามดวงอาทิตย์",
        "sun_h": "เที่ยงตามแดด",
        "sun_p": [
            "นาฬิกาไทยตั้งตามเส้นลองจิจูด 105 องศาตะวันออก ซึ่งผ่านจังหวัดอุบลราชธานี ก่อนวันที่ 1 เมษายน 2463 สยามใช้เวลาตามดวงอาทิตย์ของกรุงเทพฯ เร็วกว่ากรีนิช 6 ชั่วโมง 42 นาที 4 วินาที คืนนั้นนาฬิกาเดินหน้าไป 17 นาที 56 วินาที",
            "เชียงใหม่อยู่ทางตะวันตกของเส้นนี้หกองศา ดวงอาทิตย์ที่เชียงใหม่จึงขึ้นสูงสุดหลังเที่ยงตามนาฬิการาว 24 นาที บวกลบตามฤดู ลองเลือกเมือง",
            "คนในป่าทางเหนือดูเวลาด้วยมือ เหยียดแขนออกไป กางนิ้วเป็น<b>คืบ</b> วัดจากขอบฟ้าขึ้นไปหาดวงอาทิตย์ สูงหนึ่งคืบคือหนึ่งโมง หกคืบคือเที่ยง",
        ],
        "u_rise": "พระอาทิตย์ขึ้น",
        "u_noon": "เที่ยงตามแดด",
        "u_set": "พระอาทิตย์ตก",
        "u_spans": "ตอนนี้กี่คืบ",
        "u_line": "105°E · เวลานาฬิกา",
        "u_bmt": "เวลากรุงเทพฯ ก่อน 2463",
        "u_down": "ใต้ขอบฟ้า",
        "sun_note": "คำนวณดวงอาทิตย์ด้วยสูตรของ NOAA เวลาขึ้นและตกนับที่ขอบบนของดวงอาทิตย์ และเผื่อการหักเหของแสงในอากาศ",

        "day_kick": "หนึ่งวัน",
        "day_h": "วันหนึ่งตามนาฬิกา",
        "day": [
            ("04:00", "ตีสี่", "วัดหลายแห่งตื่น พระทำวัตรเช้า"),
            ("06:00", "หกโมงเช้า", "พระออก<b>บิณฑบาต</b>ตอนฟ้าสาง"),
            ("08:00", "แปดโมงเช้า", "วิทยุ โทรทัศน์ และเสียงตามสายเปิดเพลงชาติ ชักธงขึ้น คนหยุดยืนตรงที่เดิม"),
            ("11:00", "สิบเอ็ดโมง", "<b>เพล</b> พระฉันมื้อสุดท้ายของวัน ให้เสร็จก่อนเที่ยง"),
            ("12:00", "เที่ยง", "คนทั่วไปกิน<b>ข้าวเที่ยง</b>"),
            ("—", "บ่ายควาย", "คำบอกเวลาตามแดดแบบเก่า <b>บ่ายควาย</b> และ <b>ควายเข้าคอก</b> หมายถึงช่วงบ่ายแก่ถึงเย็น"),
            ("18:00", "หกโมงเย็น", "เพลงชาติอีกครั้ง ชักธงลง"),
            ("00:00", "เที่ยงคืน", "ในประกาศ ร.ศ. 119 เรียกว่า สองยาม คือจบยามที่สอง"),
        ],

        "pic_h": "ภาพเก่า",
        "hist_kick": "ประวัติ",
        "hist_h": "จากหอกลองถึงวิทยุ",
        "hist": [
            ("อยุธยา", "หอกลองสูงสิบวา สี่ชั้น มีกลองสามใบ ใบล่าง “ย่ำพระสุรศรี” ตีตอนพระอาทิตย์ตกให้ปิดประตูเมือง ใบกลาง “อัคคีพินาศ” ตีเมื่อไฟไหม้ ใบบน “พิฆาตไพรินทร์” ตีเมื่อข้าศึกมาประชิด"),
            ("รัชกาลที่ 1", "การพิสูจน์ด้วยการดำน้ำใช้กะลาจมเป็นเครื่องจับเวลา ทรงสงสัยว่าถ้ากะลาจมก่อนทั้งสองฝ่ายผุดขึ้นจะตัดสินอย่างไร จึงให้ตีฆ้องเป็นสัญญาณแทน"),
            ("รัชกาลที่ 2", "นาฬิกาเล็ก ๆ มาเป็นเครื่องบรรณาการจากโปรตุเกส คนสยามยังไม่ใส่เสื้อ จึงห่อไว้ในพกผ้านุ่ง เป็นที่มาของคำว่า <b>นาฬิกาพก</b>"),
            ("รัชกาลที่ 4", "ตั้งกรมนาฬิกาในวัง เทียบนาฬิกาลูกตุ้มกับนาฬิกาแดดตอนเที่ยง และออกประกาศเรื่องทุ่มโมงในราชกิจจานุเบกษา"),
            ("2432", "ใช้ปฏิทินสุริยคติเป็นปฏิทินราชการ ขึ้นปีใหม่วันที่ 1 เมษายน"),
            ("2443", "รัชกาลที่ 5 ออกประกาศใช้ทุ่มโมงยาม กำหนดชื่อชั่วโมง และบอกคำที่ใช้ผิดห้าคำ"),
            ("ยิงปืนเที่ยง", "ทหารเรือยิงปืนตอนเที่ยงให้คนตั้งนาฬิกา ต่อมาโรงไฟฟ้าใช้การกะพริบไฟตอนสองทุ่มแทน"),
            ("2463", "วันที่ 1 เมษายน สยามเปลี่ยนจากเวลาตามดวงอาทิตย์ของกรุงเทพฯ มาใช้เส้น 105 องศาตะวันออก UTC+7"),
            ("วันนี้", "กรมอุทกศาสตร์ กองทัพเรือ รักษาเวลามาตรฐานของประเทศไทย วิทยุและโทรทัศน์ประกาศเวลาตอน 08.00 น. และ 18.00 น. พร้อมเพลงชาติ"),
        ],
        "words_h": "คำศัพท์",
        "src_h": "แหล่งข้อมูล",
        "src_p": "ชื่อชั่วโมงจากราชกิจจานุเบกษา ร.ศ. 119 และวิกิพีเดียภาษาไทยและอังกฤษ ยามล้านนาจาก กรรณิการ์ วิมลเกษม กะลาลอย หอกลอง และปืนเที่ยงจาก พิศาลศรี กระต่ายทอง ในศิลปวัฒนธรรม",
        "foot": "ข้อความ CC BY 4.0, NaNoBotCo โค้ด MIT ภาพเป็นสาธารณสมบัติ จากวิกิมีเดียคอมมอนส์",
        "js": {
            "on": "", "gong": "ฆ้อง", "drum": "กลอง", "bell": "กระดิ่ง", "roll": "ย่ำ",
            "bat": "บาท", "min": "นาที", "to": "", "spans": "คืบ", "noon": "เที่ยง",
            "blk": {"ti": "ตี", "chao": "โมงเช้า", "bai": "บ่าย · เย็น", "thum": "ทุ่ม"},
            "midnight": "เที่ยงคืน", "noon_w": "เที่ยง", "cs": "จ.ศ.",
            "gloss": {"half": "half", "min": "minutes", "more": "more", "to": "to"},
        },
    },
}
